services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: vk_parser
    container_name: vk_parser
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data:/var/lib/rabbitmq